apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-szyg
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-szyg
    app.kubernetes.io/part-of: tkrw-pr714-0075-0069-app
  name: devfile-sample-szyg
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-szyg
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-szyg
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr714-0075-0069-tenant/tkrw-pr714-0075-0069-app/devfile-sample-szyg@sha256:3041b02a4938ba7c580e28c637bf7a9c1d924442142917182f99a2cb51b0c03f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
